- name: Conversion host content tasks
  block:
    - name: Display host os
      ansible.builtin.debug:
        msg: >-
          Conversion Host OS is
          {{ ansible_distribution }} {{ ansible_distribution_version }}

    - name: Include CentOS tasks
      ansible.builtin.include_tasks: centos.yml
      when: ansible_distribution in ['CentOS']

    - name: Include RHEL tasks
      ansible.builtin.include_tasks: rhel.yml
      when: ansible_distribution in ['RedHat']
