---
- name: scan available networks
  os_networks_info:
    cloud: "{{ os_migrate_src_cloud }}"
  register: src_networks_info

- name: create id-name pairs of networks to export
  set_fact:
    export_networks_ids_names: "{{ (
      src_networks_info.openstack_networks
        | json_query('[*].{name: name, id: id}')
        | sort(attribute='id') ) }}"

- name: filter names of networks to export
  set_fact:
    export_networks_ids_names: "{{ (
      export_networks_ids_names
        | os_migrate.os_migrate.stringfilter(export_networks_name_filter,
                                             attribute='name') ) }}"

- name: export network
  os_migrate.os_migrate.export_network:
    cloud: "{{ os_migrate_src_cloud }}"
    path: "{{ os_migrate_data_dir }}/networks.yml"
    name: "{{ item['id'] }}"
  loop: "{{ export_networks_ids_names }}"
