- name: clone devstack
  ansible.builtin.git:
    repo: https://opendev.org/openstack/devstack
    version: master
    dest: /home/stack/devstack
    update: no
  become: true
  become_user: stack

- name: write devstack config
  ansible.builtin.template:
    src: local.conf.j2
    dest: /home/stack/devstack/local.conf
  become: true
  become_user: stack
