---
- name: install packages for devstack
  package:
    name:
      - git
      - python2
      - python3-devel
      - tmux
    state: present

- name: remove packages which devstack does not like
  package:
    name:
      - python3-pyyaml
    state: absent

- name: create stack user
  user:
    name: stack

- name: create sudoers entry for stack
  copy:
    dest: /etc/sudoers.d/stack
    content: |
      stack ALL=(ALL) NOPASSWD:ALL
