---
- name: scan available routers
  os_migrate.os_migrate.os_routers_info:
    cloud: "{{ os_migrate_src_cloud }}"
  register: src_routers_info

- name: create id-name pairs of routers to export
  set_fact:
    export_routers_ids_names: "{{ (
      src_routers_info.openstack_routers
        | json_query('[*].{name: name, id: id}')
        | sort(attribute='id') ) }}"

- name: filter names of routers to export
  set_fact:
    export_routers_ids_names: "{{ (
      export_routers_ids_names
        | os_migrate.os_migrate.stringfilter(export_routers_name_filter,
                                             attribute='name') ) }}"

- name: export router
  os_migrate.os_migrate.export_router:
    cloud: "{{ os_migrate_src_cloud }}"
    path: "{{ os_migrate_data_dir }}/routers.yml"
    name: "{{ item['id'] }}"
  loop: "{{ export_routers_ids_names }}"
