- name: create os_migrate conversion net
  openstack.cloud.network:
    name: "{{ os_migrate_conversion_net_name }}"
    mtu: "{{ os_migrate_conversion_net_mtu }}"
    auth: "{{ os_migrate_conversion_auth }}"
    auth_type: "{{ os_migrate_conversion_auth_type|default(omit) }}"
    region_name: "{{ os_migrate_conversion_region_name|default(omit) }}"
    validate_certs: "{{ os_migrate_conversion_validate_certs|default(omit) }}"
    ca_cert: "{{ os_migrate_conversion_ca_cert|default(omit) }}"
    client_cert: "{{ os_migrate_conversion_client_cert|default(omit) }}"
    client_key: "{{ os_migrate_conversion_client_key|default(omit) }}"

- name: create os_migrate conversion subnet
  openstack.cloud.subnet:
    name: "{{ os_migrate_conversion_subnet_name }}"
    network_name: "{{ os_migrate_conversion_net_name }}"
    dns_nameservers: "{{ os_migrate_conversion_subnet_dns_nameservers }}"
    cidr: "{{ os_migrate_conversion_subnet_cidr }}"
    allocation_pool_start: "{{ os_migrate_conversion_subnet_alloc_start }}"
    allocation_pool_end: "{{ os_migrate_conversion_subnet_alloc_end }}"
    auth: "{{ os_migrate_conversion_auth }}"
    auth_type: "{{ os_migrate_conversion_auth_type|default(omit) }}"
    region_name: "{{ os_migrate_conversion_region_name|default(omit) }}"
    validate_certs: "{{ os_migrate_conversion_validate_certs|default(omit) }}"
    ca_cert: "{{ os_migrate_conversion_ca_cert|default(omit) }}"
    client_cert: "{{ os_migrate_conversion_client_cert|default(omit) }}"
    client_key: "{{ os_migrate_conversion_client_key|default(omit) }}"

- name: create os_migrate conversion router
  openstack.cloud.router:
    name: "{{ os_migrate_conversion_router_name }}"
    network: "{{ os_migrate_conversion_external_network_name }}"
    interfaces:
      - net: "{{ os_migrate_conversion_net_name }}"
        subnet: "{{ os_migrate_conversion_subnet_name }}"
        portip: "{{ os_migrate_conversion_router_ip }}"
    auth: "{{ os_migrate_conversion_auth }}"
    auth_type: "{{ os_migrate_conversion_auth_type|default(omit) }}"
    region_name: "{{ os_migrate_conversion_region_name|default(omit) }}"
    validate_certs: "{{ os_migrate_conversion_validate_certs|default(omit) }}"
    ca_cert: "{{ os_migrate_conversion_ca_cert|default(omit) }}"
    client_cert: "{{ os_migrate_conversion_client_cert|default(omit) }}"
    client_key: "{{ os_migrate_conversion_client_key|default(omit) }}"
