- name: add src conversion host to inventory
  include_tasks: conv_host_inventory.yml
  vars:
    inventory_name: os_migrate_conv_src
    os_migrate_conversion_auth: "{{ os_migrate_src_auth }}"
    os_migrate_conversion_auth_type: "{{ os_migrate_src_auth_type|default(omit) }}"
    os_migrate_conversion_region_name: "{{ os_migrate_src_region_name|default(omit) }}"
    os_migrate_conversion_validate_certs: "{{ os_migrate_src_validate_certs|default(omit) }}"
    os_migrate_conversion_ca_cert: "{{ os_migrate_src_ca_cert|default(omit) }}"
    os_migrate_conversion_client_cert: "{{ os_migrate_src_client_cert|default(omit) }}"
    os_migrate_conversion_client_key: "{{ os_migrate_src_client_key|default(omit) }}"

- name: add dst conversion host to inventory
  include_tasks: conv_host_inventory.yml
  vars:
    inventory_name: os_migrate_conv_dst
    os_migrate_conversion_auth: "{{ os_migrate_dst_auth }}"
    os_migrate_conversion_auth_type: "{{ os_migrate_dst_auth_type|default(omit) }}"
    os_migrate_conversion_region_name: "{{ os_migrate_dst_region_name|default(omit) }}"
    os_migrate_conversion_validate_certs: "{{ os_migrate_dst_validate_certs|default(omit) }}"
    os_migrate_conversion_ca_cert: "{{ os_migrate_dst_ca_cert|default(omit) }}"
    os_migrate_conversion_client_cert: "{{ os_migrate_dst_client_cert|default(omit) }}"
    os_migrate_conversion_client_key: "{{ os_migrate_dst_client_key|default(omit) }}"

- name: create folder for link keypairs
  file:
    path: "{{ os_migrate_conversion_link_keypair_private_path|dirname }}"
    state: directory

- name: generate a link keypair
  openssh_keypair:
    path: "{{ os_migrate_conversion_link_keypair_private_path }}"

- name: wait for src conversion host reachability
  wait_for:
    port: 22
    host: "{{ hostvars['os_migrate_conv_src']['ansible_ssh_host'] }}"
    search_regex: OpenSSH
    delay: 10
    timeout: 600

- name: wait for dst conversion host reachability
  wait_for:
    port: 22
    host: "{{ hostvars['os_migrate_conv_dst']['ansible_ssh_host'] }}"
    search_regex: OpenSSH
    delay: 10
    timeout: 600
