---
- name: scan available security groups
  os_migrate.os_migrate.os_security_groups_info:
    cloud: "{{ os_migrate_src_cloud }}"
  register: src_security_groups_info

- name: create id-name pairs of security groups to export
  set_fact:
    export_security_groups_ids_names: "{{ (
      src_security_groups_info.openstack_security_groups
        | json_query('[*].{name: name, id: id}')
        | sort(attribute='id') ) }}"

- name: filter names of security groups to export
  set_fact:
    export_security_groups_ids_names: "{{ (
      export_security_groups_ids_names
        | os_migrate.os_migrate.stringfilter(export_security_groups_name_filter,
                                             attribute='name') ) }}"

# In this case we will export all the security groups
# rules for all the security groups filtered before
- name: export security group rules
  os_migrate.os_migrate.export_security_group_rules:
    cloud: "{{ os_migrate_src_cloud }}"
    path: "{{ os_migrate_data_dir }}/security_group_rules.yml"
    name: "{{ item['id'] }}"
  loop: "{{ export_security_groups_ids_names }}"
