- name: validate loaded resources
  os_migrate.os_migrate.validate_resource_files:
    paths:
      - "{{ os_migrate_data_dir }}/router_interfaces.yml"
  register: router_interfaces_file_validation
  when: import_router_interfaces_validate_file

- name: stop when errors found
  fail:
    msg: "{{ router_interfaces_file_validation.errors|join(' ') }}"
  when: not ( router_interfaces_file_validation.ok | bool )

- name: read router interfaces resource file
  os_migrate.os_migrate.read_resources:
    path: "{{ os_migrate_data_dir }}/router_interfaces.yml"
  register: read_router_interfaces

- name: import router interfaces
  os_migrate.os_migrate.import_router_interface:
    auth: "{{ os_migrate_dst_auth }}"
    auth_type: "{{ os_migrate_dst_auth_type|default(omit) }}"
    region_name: "{{ os_migrate_dst_region_name|default(omit) }}"
    data: "{{ item }}"
  loop: "{{ read_router_interfaces.resources }}"
