---
namespace: os_migrate
name: os_migrate
version: 0.1.0
readme: README.md
authors:
  - Jiri Stransky <jistr@redhat.com>
  - Carlos Camacho <ccamacho@redhat.com>
  - Ryan Brady <rbrady@redhat.com>
description: OpenStack tenant migration tooling
license:
  - Apache-2.0
license_file: ''
tags: []
dependencies: {}
repository: ''
documentation: ''
homepage: ''
issues: ''
