- name: validate loaded resources
  os_migrate.os_migrate.validate_resource_files:
    paths:
      - "{{ os_migrate_data_dir }}/workloads.yml"
  register: workloads_file_validation
  when: import_workloads_validate_file

- name: stop when errors found
  fail:
    msg: "{{ workloads_file_validation.errors|join(' ') }}"
  when: not ( workloads_file_validation.ok | bool )

- name: read workloads resource file
  os_migrate.os_migrate.read_resources:
    path: "{{ os_migrate_data_dir }}/workloads.yml"
  register: read_workloads

- name: get source conversion host address
  os_migrate.os_migrate.os_conversion_host_info:
    auth: "{{ os_migrate_src_auth }}"
    auth_type: "{{ os_migrate_src_auth_type|default(omit) }}"
    region_name: "{{ os_migrate_src_region_name|default(omit) }}"
    server: "{{ os_migrate_src_conversion_host }}"
    filters: "{{ os_migrate_src_filters }}"
    validate_certs: "{{ os_migrate_src_validate_certs|default(omit) }}"
    ca_cert: "{{ os_migrate_src_ca_cert|default(omit) }}"
    client_cert: "{{ os_migrate_src_client_cert|default(omit) }}"
    client_key: "{{ os_migrate_src_client_key|default(omit) }}"
  register: os_src_conversion_host_info

- name: check source conversion host status
  fail:
    msg: The source conversion host is not running!
  when: os_src_conversion_host_info.openstack_conversion_host.status != "ACTIVE"

- name: get destination conversion host address
  os_migrate.os_migrate.os_conversion_host_info:
    auth: "{{ os_migrate_dst_auth }}"
    auth_type: "{{ os_migrate_dst_auth_type|default(omit) }}"
    region_name: "{{ os_migrate_dst_region_name|default(omit) }}"
    server: "{{ os_migrate_dst_conversion_host }}"
    # FIXME: add filters
    validate_certs: "{{ os_migrate_dst_validate_certs|default(omit) }}"
    ca_cert: "{{ os_migrate_dst_ca_cert|default(omit) }}"
    client_cert: "{{ os_migrate_dst_client_cert|default(omit) }}"
    client_key: "{{ os_migrate_dst_client_key|default(omit) }}"
  register: os_dst_conversion_host_info

- name: check destination conversion host status
  fail:
    msg: The destination conversion host is not running!
  when: os_dst_conversion_host_info.openstack_conversion_host.status != "ACTIVE"

- name: import workloads
  include_tasks: workload.yml
  loop: "{{ read_workloads.resources }}"
