- name: scan available security groups
  os_migrate.os_migrate.os_security_groups_info:
    cloud: "{{ os_migrate_src_cloud }}"
  register: src_security_groups_info

- name: filter names of security_groups to export
  set_fact:
    export_security_groups_names: "{{ src_security_groups_info.openstack_security_groups | json_query('[*].name') | sort | os_migrate.os_migrate.stringfilter(export_security_groups_name_filter) }}"

- name: export security groups
  os_migrate.os_migrate.export_security_group:
    cloud: "{{ os_migrate_src_cloud }}"
    path: "{{ os_migrate_data_dir }}/security_groups.yml"
    name: "{{ item }}"
  loop: "{{ export_security_groups_names }}"
