- name: validate loaded resources
  os_migrate.os_migrate.validate_resource_files:
    paths:
      - "{{ os_migrate_data_dir }}/subnets.yml"
  register: subnets_file_validation
  when: import_subnets_validate_file

- name: stop when errors found
  fail:
    msg: "{{ subnets_file_validation.errors|join(' ') }}"
  when: not ( subnets_file_validation.ok | bool )

- name: read subnets resource file
  os_migrate.os_migrate.read_resources:
    path: "{{ os_migrate_data_dir }}/subnets.yml"
  register: read_networks

- name: import subnets
  os_migrate.os_migrate.import_subnet:
    auth: "{{ os_migrate_dst_auth }}"
    auth_type: "{{ os_migrate_dst_auth_type|default(omit) }}"
    region_name: "{{ os_migrate_dst_region_name|default(omit) }}"
    data: "{{ item }}"
  loop: "{{ read_networks.resources }}"
