- name: read networks resource file
  os_migrate.os_migrate.read_resources:
    path: "{{ os_migrate_data_dir }}/networks.yml"
  register: read_networks

- name: import networks
  os_migrate.os_migrate.import_network:
    cloud: "{{ os_migrate_dst_cloud }}"
    data: "{{ item }}"
  loop: "{{ read_networks.resources }}"
