---
- name: validate loaded resources
  os_migrate.os_migrate.validate_resource_files:
    paths:
      - "{{ os_migrate_data_dir }}/networks.yml"
  register: networks_file_validation
  when: import_networks_validate_file

- name: stop when errors found
  fail:
    msg: "{{ networks_file_validation.errors|join(' ') }}"
  when: not networks_file_validation.ok

- name: read networks resource file
  os_migrate.os_migrate.read_resources:
    path: "{{ os_migrate_data_dir }}/networks.yml"
  register: read_networks

- name: import networks
  os_migrate.os_migrate.import_network:
    cloud: "{{ os_migrate_dst_cloud }}"
    data: "{{ item }}"
  loop: "{{ read_networks.resources }}"
